import { DemoProfile, ExposureInputs } from './types';
import { DEFAULT_INPUTS } from './constants';

export const DEMO_PROFILES: DemoProfile[] = [
  {
    id: 'meridian',
    name: 'Meridian Financial Group',
    industry: 'Financial Services',
    size: 'Enterprise (1000–10000)',
    revenue: '€500M–€5B',
    description: 'High-frequency autonomous trading decisions, deeply integrated with core banking infrastructure, minimal human oversight cadence.',
    afi: 2.23,
    band: 'Fragile',
    premiumEstimate: '€420k–€680k',
    useCases: ['Autonomous Operations', 'Fraud Detection', 'Risk Assessment', 'Predictive Analytics'],
    sliders: {
      automation: 4, criticality: 5, integrationDepth: 4, workflowBreadth: 4,
      executionAuthority: 4, actionDensity: 3, toolCallScope: 4,
      oversightLevel: 2, reviewCadence: 2, sunsetPolicy: 1, switchingCost: 4, portability: 4,
      multiAgent: 3, toolCallAuthority: 4, persistentMemory: 2, humanCheckpoints: 2,
      hallucinationLiability: 4, deepfakeFraud: 3, promptInjection: 3, modelDrift: 4, algorithmicBias: 3,
      shadowAI: 4, explainabilityGap: 4, dataIntegrity: 4, esgLiability: 3,
      dataPoisoning: 3, adversarialAttack: 4, privacyBreach: 3, ipInfringement: 3,
      cloudConcentration: 2, modelConcentration: 2, gpuConcentration: 2, crossVendorContagion: 2,
    },
    dependencies: ['OpenAI', 'Azure OpenAI'],
    signals: [
      'Autonomous trading execution without re-authorization (18 months)',
      'Single-provider OpenAI dependency',
      'Responsibility Fragmentation Score: 84',
      'No formal governance review cycle',
      'Art. 72 post-market monitoring: not conducted',
    ],
  },
  {
    id: 'healthpath',
    name: 'HealthPath AI',
    industry: 'Healthcare',
    size: 'Mid-Market (250–1000)',
    revenue: '€50M–€500M',
    description: 'Clinical decision support with partial human-in-the-loop. High criticality and elevated automation with two-provider diversification.',
    afi: 1.08,
    band: 'Sensitive',
    premiumEstimate: '€210k–€340k',
    useCases: ['Decision Support', 'Predictive Analytics', 'Risk Assessment'],
    sliders: {
      automation: 4, criticality: 5, integrationDepth: 3, workflowBreadth: 3,
      executionAuthority: 3, actionDensity: 3, toolCallScope: 3,
      oversightLevel: 2, reviewCadence: 3, sunsetPolicy: 2, switchingCost: 3, portability: 3,
      multiAgent: 1, toolCallAuthority: 2, persistentMemory: 1, humanCheckpoints: 4,
      hallucinationLiability: 3, deepfakeFraud: 1, promptInjection: 2, modelDrift: 3, algorithmicBias: 4,
      shadowAI: 2, explainabilityGap: 3, dataIntegrity: 2, esgLiability: 2,
      dataPoisoning: 2, adversarialAttack: 2, privacyBreach: 4, ipInfringement: 1,
      cloudConcentration: 3, modelConcentration: 3, gpuConcentration: 3, crossVendorContagion: 3,
    },
    dependencies: ['Anthropic', 'Google DeepMind'],
    signals: [
      'High-risk medical decisions (EU AI Act Annex III)',
      'Quarterly governance review in place',
      'Human physician confirmation required',
      'Some hallucination risk in patient-facing outputs',
    ],
  },
  {
    id: 'lexcore',
    name: 'LexCore Systems',
    industry: 'Legal',
    size: 'Mid-Market (250–1000)',
    revenue: '€10M–€50M',
    description: 'Autonomous contract review deeply embedded in case management workflows. Single provider, no sunset policy, extreme switching cost.',
    afi: 1.85,
    band: 'Fragile',
    premiumEstimate: '€350k–€550k',
    useCases: ['Document Processing', 'Decision Support', 'Compliance Monitoring'],
    sliders: {
      automation: 4, criticality: 4, integrationDepth: 5, workflowBreadth: 3,
      executionAuthority: 3, actionDensity: 4, toolCallScope: 3,
      oversightLevel: 2, reviewCadence: 1, sunsetPolicy: 1, switchingCost: 5, portability: 5,
      multiAgent: 2, toolCallAuthority: 3, persistentMemory: 4, humanCheckpoints: 2,
      hallucinationLiability: 1, deepfakeFraud: 1, promptInjection: 1, modelDrift: 1, algorithmicBias: 1,
      shadowAI: 3, explainabilityGap: 3, dataIntegrity: 4, esgLiability: 4,
      dataPoisoning: 2, adversarialAttack: 3, privacyBreach: 2, ipInfringement: 4,
      cloudConcentration: 2, modelConcentration: 2, gpuConcentration: 2, crossVendorContagion: 2,
    },
    dependencies: ['OpenAI'],
    signals: [
      'Single provider — extreme concentration risk',
      'No sunset policy — continuation risk critical',
      'Switching cost 5/5 — structural lock-in',
      'Persistent memory with no re-authorization',
    ],
  },
  {
    id: 'retailflow',
    name: 'RetailFlow',
    industry: 'Retail / E-Commerce',
    size: 'Enterprise (1000–10000)',
    revenue: '€500M–€5B',
    description: 'AI-driven demand forecasting and personalisation engine across 12 markets. Moderate integration depth with cloud-native architecture.',
    afi: 0.92,
    band: 'Sensitive',
    premiumEstimate: '€140k–€220k',
    useCases: ['Predictive Analytics', 'Customer Service Automation', 'Decision Support'],
    sliders: {
      automation: 3, criticality: 3, integrationDepth: 3, workflowBreadth: 4,
      executionAuthority: 3, actionDensity: 3, toolCallScope: 3,
      oversightLevel: 3, reviewCadence: 3, sunsetPolicy: 3, switchingCost: 2, portability: 3,
      multiAgent: 1, toolCallAuthority: 2, persistentMemory: 2, humanCheckpoints: 3,
      hallucinationLiability: 1, deepfakeFraud: 1, promptInjection: 1, modelDrift: 1, algorithmicBias: 1,
      shadowAI: 3, explainabilityGap: 3, dataIntegrity: 3, esgLiability: 3,
      dataPoisoning: 1, adversarialAttack: 2, privacyBreach: 2, ipInfringement: 2,
      cloudConcentration: 3, modelConcentration: 3, gpuConcentration: 3, crossVendorContagion: 3,
    },
    dependencies: ['AWS Bedrock', 'Anthropic'],
    signals: [
      'Moderate integration depth — some exit flexibility',
      'Multi-provider strategy reduces concentration',
      'Quarterly governance review in place',
    ],
  },
  {
    id: 'civicai',
    name: 'CivicAI Gov',
    industry: 'Government',
    size: 'Large',
    description: 'Public sector drafting assistant with mandatory quarterly re-authorisation, comprehensive human oversight, in-house model deployment.',
    afi: 0.47,
    band: 'Stable',
    premiumEstimate: '€80k–€140k',
    useCases: ['Decision Support', 'Document Processing', 'Compliance Monitoring'],
    sliders: {
      automation: 2, criticality: 3, integrationDepth: 2, workflowBreadth: 2,
      executionAuthority: 1, actionDensity: 1, toolCallScope: 2,
      oversightLevel: 5, reviewCadence: 5, sunsetPolicy: 4, switchingCost: 2, portability: 2,
      multiAgent: 1, toolCallAuthority: 1, persistentMemory: 1, humanCheckpoints: 5,
      hallucinationLiability: 1, deepfakeFraud: 1, promptInjection: 1, modelDrift: 1, algorithmicBias: 1,
      shadowAI: 1, explainabilityGap: 1, dataIntegrity: 1, esgLiability: 1,
      dataPoisoning: 1, adversarialAttack: 1, privacyBreach: 1, ipInfringement: 1,
      cloudConcentration: 5, modelConcentration: 4, gpuConcentration: 5, crossVendorContagion: 5,
    },
    dependencies: ['Custom / In-House'],
    signals: [
      'Mandatory quarterly re-authorization',
      'In-house model (no external dependency)',
      'Comprehensive human oversight',
      'Documented sunset procedures',
      'Multi-provider strategy for resilience',
    ],
  },
];

export function applyDemoProfile(profile: DemoProfile): ExposureInputs {
  return {
    ...DEFAULT_INPUTS,
    companyName: profile.name,
    industry: profile.industry,
    size: profile.size,
    revenue: '',
    useCases: profile.useCases || [],
    providers: profile.dependencies,
    automation: profile.sliders.automation ?? 3,
    criticality: profile.sliders.criticality ?? 3,
    integrationDepth: profile.sliders.integrationDepth ?? 3,
    workflowBreadth: profile.sliders.workflowBreadth ?? 3,
    executionAuthority: profile.sliders.executionAuthority ?? 3,
    actionDensity: profile.sliders.actionDensity ?? 3,
    toolCallScope: profile.sliders.toolCallScope ?? 3,
    oversightLevel: profile.sliders.oversightLevel ?? 3,
    reviewCadence: profile.sliders.reviewCadence ?? 3,
    sunsetPolicy: profile.sliders.sunsetPolicy ?? 3,
    switchingCost: profile.sliders.switchingCost ?? 3,
    portability: profile.sliders.portability ?? 3,
    multiAgent: profile.sliders.multiAgent ?? 1,
    toolCallAuthority: profile.sliders.toolCallAuthority ?? 1,
    persistentMemory: profile.sliders.persistentMemory ?? 1,
    humanCheckpoints: profile.sliders.humanCheckpoints ?? 3,
    hallucinationLiability: profile.sliders.hallucinationLiability ?? 1,
    deepfakeFraud: profile.sliders.deepfakeFraud ?? 1,
    promptInjection: profile.sliders.promptInjection ?? 1,
    modelDrift: profile.sliders.modelDrift ?? 1,
    algorithmicBias: profile.sliders.algorithmicBias ?? 1,
    shadowAI: profile.sliders.shadowAI ?? 3,
    explainabilityGap: profile.sliders.explainabilityGap ?? 3,
    dataIntegrity: profile.sliders.dataIntegrity ?? 2,
    esgLiability: profile.sliders.esgLiability ?? 2,
    cloudConcentration: profile.sliders.cloudConcentration ?? 3,
    modelConcentration: profile.sliders.modelConcentration ?? 3,
    gpuConcentration: profile.sliders.gpuConcentration ?? 3,
    crossVendorContagion: profile.sliders.crossVendorContagion ?? 3,
    dataPoisoning: profile.sliders.dataPoisoning ?? 1,
    adversarialAttack: profile.sliders.adversarialAttack ?? 1,
    privacyBreach: profile.sliders.privacyBreach ?? 1,
    ipInfringement: profile.sliders.ipInfringement ?? 1,
  } as ExposureInputs;
}
