import { DemoProfile, ExposureInputs } from './types';
import { DEFAULT_INPUTS } from './constants';

export const DEMO_PROFILES: DemoProfile[] = [
  {
    name: 'Meridian Financial',
    industry: 'Financial Services',
    useCases: ['Decision Support', 'Autonomous Operations', 'Fraud Detection'],
    providers: ['OpenAI', 'Azure OpenAI'],
    sliders: {
      automation: 4, criticality: 5, integrationDepth: 4, workflowBreadth: 4,
      executionAuthority: 4, actionDensity: 3, toolCallScope: 4, oversightLevel: 2,
      reviewCadence: 2, sunsetPolicy: 1, switchingCost: 4, portability: 4,
      multiAgent: 3, toolCallAuthority: 4, persistentMemory: 2, humanCheckpoints: 2,
      hallucinationLiability: 3, deepfakeFraud: 2, promptInjection: 3, modelDrift: 3,
      algorithmicBias: 2, shadowAI: 3, explainabilityGap: 3, dataIntegrity: 2, esgLiability: 2,
      cloudConcentration: 2, modelConcentration: 2, gpuConcentration: 3, crossVendorContagion: 2,
    },
    note: 'Deep integration, minimal oversight, single-provider dependence',
    band: 'Fragile',
    premiumEstimate: '€420k–€680k',
    icon: '🏦',
  },
  {
    name: 'HealthPath AI',
    industry: 'Healthcare',
    useCases: ['Risk Assessment', 'Document Processing', 'Compliance Monitoring'],
    providers: ['Anthropic', 'Google DeepMind'],
    sliders: {
      automation: 4, criticality: 5, integrationDepth: 3, workflowBreadth: 3,
      executionAuthority: 3, actionDensity: 3, toolCallScope: 3, oversightLevel: 2,
      reviewCadence: 3, sunsetPolicy: 2, switchingCost: 3, portability: 3,
      multiAgent: 1, toolCallAuthority: 2, persistentMemory: 1, humanCheckpoints: 4,
      hallucinationLiability: 2, deepfakeFraud: 1, promptInjection: 2, modelDrift: 2,
      algorithmicBias: 3, shadowAI: 2, explainabilityGap: 2, dataIntegrity: 2, esgLiability: 1,
      cloudConcentration: 3, modelConcentration: 3, gpuConcentration: 3, crossVendorContagion: 3,
    },
    note: 'Clinical decision support, partial human-in-the-loop, moderate governance',
    band: 'Sensitive',
    premiumEstimate: '€180k–€320k',
    icon: '🏥',
  },
  {
    name: 'LexCore Systems',
    industry: 'Legal',
    useCases: ['Document Processing', 'Compliance Monitoring', 'Risk Assessment'],
    providers: ['OpenAI', 'Anthropic'],
    sliders: {
      automation: 4, criticality: 4, integrationDepth: 4, workflowBreadth: 3,
      executionAuthority: 3, actionDensity: 3, toolCallScope: 3, oversightLevel: 2,
      reviewCadence: 2, sunsetPolicy: 2, switchingCost: 4, portability: 4,
      multiAgent: 2, toolCallAuthority: 3, persistentMemory: 3, humanCheckpoints: 2,
      hallucinationLiability: 4, deepfakeFraud: 1, promptInjection: 2, modelDrift: 2,
      algorithmicBias: 2, shadowAI: 3, explainabilityGap: 4, dataIntegrity: 2, esgLiability: 1,
      cloudConcentration: 2, modelConcentration: 2, gpuConcentration: 3, crossVendorContagion: 2,
    },
    note: 'Legal AI with high hallucination risk and explainability gaps',
    band: 'Fragile',
    premiumEstimate: '€350k–€550k',
    icon: '⚖️',
  },
  {
    name: 'RetailFlow',
    industry: 'Retail / E-Commerce',
    useCases: ['Customer Service Automation', 'Predictive Analytics', 'Fraud Detection'],
    providers: ['OpenAI', 'AWS Bedrock'],
    sliders: {
      automation: 3, criticality: 3, integrationDepth: 3, workflowBreadth: 3,
      executionAuthority: 2, actionDensity: 3, toolCallScope: 2, oversightLevel: 3,
      reviewCadence: 3, sunsetPolicy: 3, switchingCost: 3, portability: 3,
      multiAgent: 1, toolCallAuthority: 2, persistentMemory: 2, humanCheckpoints: 3,
      hallucinationLiability: 2, deepfakeFraud: 2, promptInjection: 2, modelDrift: 2,
      algorithmicBias: 2, shadowAI: 3, explainabilityGap: 2, dataIntegrity: 2, esgLiability: 2,
      cloudConcentration: 3, modelConcentration: 3, gpuConcentration: 3, crossVendorContagion: 3,
    },
    note: 'Customer-facing AI with moderate governance, standard risk profile',
    band: 'Sensitive',
    premiumEstimate: '€120k–€240k',
    icon: '🛒',
  },
  {
    name: 'CivicAI Gov',
    industry: 'Government',
    useCases: ['Document Processing', 'Compliance Monitoring'],
    providers: ['Custom / In-House'],
    sliders: {
      automation: 2, criticality: 3, integrationDepth: 2, workflowBreadth: 2,
      executionAuthority: 1, actionDensity: 1, toolCallScope: 2, oversightLevel: 5,
      reviewCadence: 5, sunsetPolicy: 4, switchingCost: 2, portability: 2,
      multiAgent: 1, toolCallAuthority: 1, persistentMemory: 1, humanCheckpoints: 5,
      hallucinationLiability: 1, deepfakeFraud: 1, promptInjection: 1, modelDrift: 1,
      algorithmicBias: 1, shadowAI: 1, explainabilityGap: 1, dataIntegrity: 1, esgLiability: 1,
      cloudConcentration: 4, modelConcentration: 5, gpuConcentration: 4, crossVendorContagion: 4,
    },
    note: 'Public-sector drafting assistant, quarterly re-authorisation, strong oversight',
    band: 'Stable',
    premiumEstimate: '€45k–€90k',
    icon: '🏛️',
  },
];

export function applyDemoProfile(profile: DemoProfile): ExposureInputs {
  return {
    ...DEFAULT_INPUTS,
    companyName: profile.name,
    industry: profile.industry,
    useCases: profile.useCases,
    providers: profile.providers,
    automation: profile.sliders.automation ?? 3,
    criticality: profile.sliders.criticality ?? 3,
    integrationDepth: profile.sliders.integrationDepth ?? 3,
    workflowBreadth: profile.sliders.workflowBreadth ?? 3,
    executionAuthority: profile.sliders.executionAuthority ?? 3,
    actionDensity: profile.sliders.actionDensity ?? 3,
    toolCallScope: profile.sliders.toolCallScope ?? 3,
    oversightLevel: profile.sliders.oversightLevel ?? 3,
    reviewCadence: profile.sliders.reviewCadence ?? 3,
    sunsetPolicy: profile.sliders.sunsetPolicy ?? 3,
    switchingCost: profile.sliders.switchingCost ?? 3,
    portability: profile.sliders.portability ?? 3,
    multiAgent: profile.sliders.multiAgent ?? 1,
    toolCallAuthority: profile.sliders.toolCallAuthority ?? 1,
    persistentMemory: profile.sliders.persistentMemory ?? 1,
    humanCheckpoints: profile.sliders.humanCheckpoints ?? 3,
    hallucinationLiability: profile.sliders.hallucinationLiability ?? 1,
    deepfakeFraud: profile.sliders.deepfakeFraud ?? 1,
    promptInjection: profile.sliders.promptInjection ?? 1,
    modelDrift: profile.sliders.modelDrift ?? 1,
    algorithmicBias: profile.sliders.algorithmicBias ?? 1,
    shadowAI: profile.sliders.shadowAI ?? 3,
    explainabilityGap: profile.sliders.explainabilityGap ?? 3,
    dataIntegrity: profile.sliders.dataIntegrity ?? 2,
    esgLiability: profile.sliders.esgLiability ?? 2,
    cloudConcentration: profile.sliders.cloudConcentration ?? 3,
    modelConcentration: profile.sliders.modelConcentration ?? 3,
    gpuConcentration: profile.sliders.gpuConcentration ?? 3,
    crossVendorContagion: profile.sliders.crossVendorContagion ?? 3,
  };
}
